name: Build and Push Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      isLatest:
        required: true
        type: boolean
      composeTag:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug secrets 
        run: | 
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}" 
          echo "Token length: ${#DOCKERHUB_TOKEN}"
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }} \
            .

      - name: Tag as latest (only for releases)
        if: ${{ inputs.isLatest == true }}
        run: |
          docker tag \
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }} \
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }}

      - name: Push latest tag
        if: ${{ inputs.isLatest == true }}
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        
      - name: Install ORAS CLI 
        run: | 
          curl -sSfL https://github.com/oras-project/oras/releases/latest/download/oras_1.2.0_linux_amd64.tar.gz -o oras.tar.gz 
          tar -xzf oras.tar.gz oras 
          sudo mv oras /usr/local/bin/
      - name: Publish docker-compose.yml as OCI artifact
        if: ${{ inputs.composeTag != '' }}
        run: |
          oras push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.composeTag }} \
            --artifact-type application/vnd.docker.compose \
            docker/docker-compose.yml
