name: Build and Push Image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      isLatest:
        required: true
        type: boolean
      composeTag:
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug secrets 
        run: | 
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}" 
          echo "Token length: ${#DOCKERHUB_TOKEN}"
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }} \
            .

      - name: Tag as latest (only for releases)
        if: ${{ inputs.isLatest == true }}
        run: |
          docker tag \
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }} \
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ inputs.tag }}

      - name: Push latest tag
        if: ${{ inputs.isLatest == true }}
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        
      - name: Setup ORAS CLI
        uses: oras-project/setup-oras@v1

      - name: Login to Docker Hub with ORAS
        env:
          REGISTRY: registry-1.docker.io
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${TOKEN}" | oras login "${REGISTRY}" -u "${USERNAME}" --password-stdin
      
      - name: Push docker-compose as OCI artifact
        env:
          REGISTRY: registry-1.docker.io
          COMPOSE_REPO: ivicenter2018/3dmanager-app
          TAG: ${{ inputs.composeTag }}
        run: |
          oras push "${REGISTRY}/${COMPOSE_REPO}:${TAG}" \
            docker/docker-compose.yml:application/vnd.docker.compose.config.v1+yaml

