name:  CI Full

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  server:
    name: Server (unitary + integration + sistem)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .Code/3DMANAGER-APP/3DMANAGER-APP.Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Compile
        run: dotnet build --no-restore --configuration Release

      - name: Execute full test (.NET)
        run: dotnet test --configuration Release --verbosity normal

  client:
    name: Cliente (unitary + integration + E2E)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Code/3DMANAGER-APP/3dmanager-app.client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build

      - name: Unitary tests  / integration (Vitest)
        run: npm run test -- --run

      - name: Tests E2E (Playwright)
        run: npx playwright test --reporter=dot